### ISSUE TITLE
New to SASS/Grunt question

### ISSUE THREAD

**Issue by joshrogersdesign** [gregrickaby/genesis-sample#4]
Forgive my lack of understanding...

But is there a way to upload this great SASS sample into a new Genesis theme? Do I just replace all the css files in my Genesis theme with the ones in this directory? 

Thanks

**Comment by RickeyMessick** [comment]
You do not alter the genesis theme itself.  You download the child theme
from "https://github.com/gregrickaby/genesis-sample" and name it whatever
you want and it get parent structure from genesis and you can make any
modifications in it.

Does that  make sense?

Here is explanation of child theme.
https://codex.wordpress.org/Child_Themes

**Comment by joshrogersdesign** [comment]
I'm getting closer. 

I'm about to download a child theme from Studiopress that has a lot of great built in features I like. But I want to use the SASS/Grunt setup offered by Rickaby. I just don't see how to connect those together. I understand renaming Genesis-Sample and making that the primary theme!

**Comment by RickeyMessick** [comment]
Alot of times i will download the child theme from Genesis and add the code
and css into my rickaby starter theme.  No good way there.  But that will
help you understand how genesis works.

**Comment by joshrogersdesign** [comment]
Okay, so just add all of the Studiopress theme files to the Rickaby theme? Sounds tedious but doable! Is there something more to it that makes it hard?

Basically this Rickaby sample theme is perfect if you are amazing with Genesis and basically want to develop your own custom Genesis theme?

"An eye for an eye leaves the whole world blind"

On Aug 19, 2015, at 2:16 PM, Rickey Messick <notifications@github.com<mailto:notifications@github.com>> wrote:

Alot of times i will download the child theme from Genesis and add the code
and css into my rickaby starter theme. No good way there. But that will
help you understand how genesis works.



On Wed, Aug 19, 2015 at 2:04 PM joshrogersdesign <notifications@github.com<mailto:notifications@github.com>>
wrote:

> I'm getting closer.
>
> I'm about to download a child theme from Studiopress that has a lot of
> great built in features I like. But I want to use the SASS/Grunt setup
> offered by Rickaby. I just don't see how to connect those together. I
> understand renaming Genesis-Sample and making that the primary theme!
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/gregrickaby/genesis-sample/issues/4#issuecomment-132744486>
> .
>

-

**Comment by joshrogersdesign** [comment]
Sounds like I might be better off installing SASS / Grunt and all if its tasks on the Studiopress theme manually?

"An eye for an eye leaves the whole world blind"

On Aug 19, 2015, at 2:16 PM, Rickey Messick <notifications@github.com<mailto:notifications@github.com>> wrote:

Alot of times i will download the child theme from Genesis and add the code
and css into my rickaby starter theme. No good way there. But that will
help you understand how genesis works.



On Wed, Aug 19, 2015 at 2:04 PM joshrogersdesign <notifications@github.com<mailto:notifications@github.com>>
wrote:

> I'm getting closer.
>
> I'm about to download a child theme from Studiopress that has a lot of
> great built in features I like. But I want to use the SASS/Grunt setup
> offered by Rickaby. I just don't see how to connect those together. I
> understand renaming Genesis-Sample and making that the primary theme!
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/gregrickaby/genesis-sample/issues/4#issuecomment-132744486>
> .
>

-

**Comment by RickeyMessick** [comment]
Once you get into it you will realize that to customize the genesis child
theme it is not that much php code.  More css than anything.

**Comment by joshrogersdesign** [comment]
Okay - made a lot of progress today! I have Genesis framework and a Studiopress child theme (Swank) installed and activated. The child theme has all of Rickaby's SASS files, partials, etc. and I have Grunt working to minify the CSS.

The only problem now is every time I save an edit to a partial and save it- Grunt compiles the CSS, but it overrides the style.css and style.min.css of the Child theme with the CSS of Genesis Framework instead of just adding the changes to the style.css that's in the theme folder.

Any thoughts on that? I am so close here! Just need to figure out this last bit.

**Comment by RickeyMessick** [comment]
I do not understand.  The genesis theme you do not touch at all.  just have
it in your theme folder.  That is it.  All changes go in your child theme
from Gregg.  Take the Swank theme and move the code in it over to the child
them from Gregg.

**Comment by joshrogersdesign** [comment]
I have Genesis in my directory, as well as the Genesis-Sample. When I move the Swank css and php theme files over to Genesis-Sample it overwrites the files and replaces them with the desired Swank theme files - good so far. 

Then from a Terminal window that is targeting the Genesis-Sample theme folder I do an npm install and the run grunt watch - still all good, grunt starts watching that folder for changes in any .scss files.

Now when I go back to partials folder in Sublime Text and make an edit to the code and save it, grunt makes its noise indicating that all is well and that grunt has accomplished its task - still good!

Except when I look at the style.css and style.min.css all of the code has been overwritten with Genesis 2.0.1 CSS in the style.min.css as well and all of the Swank CSS is gone.

**Comment by joshrogersdesign** [comment]
Now that I have written it all out and thinking about it - do I need to replace all of the .scss files with the CSS from Swank? Does that even make sense?

**Comment by RickeyMessick** [comment]
Yes sir.   You got it.  You have to split back out the style.css into your
scss files.  Or have one big one.  Your preference.

**Comment by joshrogersdesign** [comment]
Thanks for your help Rickey. I this is a good into the next level of development.

One last question. I have decided to split the CSS into the SCSS partials provided by Rickaby - will Wordpress still read the unchanged - orginal Genesis framework as the parent theme and my new frankenstein Swank theme as the child? Or is further enqueuing necessary to make that relationship known to Wordpress?

**Comment by RickeyMessick** [comment]
At the top of your stylesheet there is a parent theme: Genesis that's what
tells word press what the parent is so whichever when you have active is
going to read from and then also the parent of it sorry this is through
Siri on my phone

**Comment by joshrogersdesign** [comment]
Awesome, yes on my style.scss and style.css of Swank the template is specified as "genesis" so I am good there!

Thank you
