### ISSUE TITLE
Warning: Missing argument 2 for wp_register_style(), called in functions.php on line 29 and defined in \wp-includes\functions.wp-styles.php on line 113

### ISSUE THREAD

**Issue by dpav02** [gregrickaby/genesis-sample#9]
I tried to set this up locally and I'm getting an error based on the functions.php file....

wp_register_style( 'genesis-sample-theme' );

Honestly, you have another register block below that one. I removed line 29 from your function.php and it compiles. 

I'll be submitting a pull request.

**Comment by gregrickaby** [comment]
See #11
